backend:
  name: git-gateway
  branch: master

local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: 'home'
    label: 'Home'
    files:
      - label: 'Home'
        name: 'home'
        file: 'content/home.md'
        create: true
        slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
        editor:
          preview: false
        fields:
          - label: Gallery
            name: gallery
            widget: list
            allow_add: true
            fields:
              - label: Image
                name: image
                widget: image
              - label: Title
                name: title
                widget: string
              - label: URL
                name: url
                widget: string
          - label: Sections
            name: sections
            widget: list
            types:
              - label: Text
                name: text
                widget: object
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Text
                    name: text
                    widget: markdown
              - label: Image
                name: image
                widget: object
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Images
                    name: images
                    widget: list
                    fields:
                      - label: Image
                        name: image
                        widget: image

