backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: static/img
public_folder: /img

gallery: &GALLERY
  - label: Title
    name: title
    widget: string
  - label: SubTitle
    name: subTitle
    widget: string
  - label: URL
    name: url
    widget: string
  - label: Image
    name: image
    widget: image

page_builder: &PAGE_BUILDER
  - label: Text
    name: text
    widget: object
    allow_add: true
    summary: 'Text: {{title}}'
    fields:
      - label: Title
        name: title
        required: false
        widget: string
      - label: Content
        name: content
        widget: markdown
      - label: Columns
        name: columns
        widget: number
        default: 1
        value_type: int
        min: 1
        max: 2
        step: 1
      - label: Color
        name: color
        widget: select
        multiple: false
        options: ['orange', 'red', 'pink', 'green', 'white', 'skin']
      - label: Margins
        name: margins
        required: false
        widget: boolean
      - label: Center
        name: center
        required: false
        widget: boolean
      - label: Serif
        name: serif
        required: false
        widget: boolean
  - label: Gallery
    name: gallery
    summary: Gallery
    fields:
      - label: Images
        name: images
        widget: list
        label_singular: image
        fields:
          - label: Title
            name: title
            widget: string
          - label: URL
            name: url
            widget: string
          - label: Image
            name: image
            widget: image
  - label: Image
    name: image
    summary: Image
    fields:
      - label: Image
        name: image
        widget: image
  - label: Links
    name: links
    summary: Links
    fields:
      - label: Links
        name: links
        widget: list
        fields:
          - lable: Title
            name: title
            widget: string
          - label: Text
            name: text
            widget: string
          - label: Link
            name: link
            widget: string

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: Home
        name: home
        file: content/home.md
        create: true
        slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
        editor:
          preview: false
        fields:
          - label: Gallery
            name: gallery
            widget: list
            allow_add: true
            label_singular: image
            summary: '{{title}}'
            fields: *GALLERY

          - label: Sections
            name: sections
            widget: list
            collapsed: true
            types: *PAGE_BUILDER

      - label: Chi siamo
        name: about
        file: content/about.md
        create: true
        slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
        editor:
          preview: false
        fields:
          - label: Sections
            name: sections
            widget: list
            types: *PAGE_BUILDER

      - label: Novita
        name: novita
        file: content/novita.md
        editor:
          preview: false
        fields:
          - label: Gallery
            name: gallery
            widget: list
            allow_add: true
            label_singular: image
            summary: '{{title}}'
            fields: *GALLERY
          - label: Sections
            name: sections
            widget: list
            types: *PAGE_BUILDER

      - label: Contatti
        name: contatti
        file: content/contatti.md
        editor:
          preview: false
        fields:
          - label: Address
            name: address
            widget: markdown
          - label: Phone
            name: phone
            widget: string
          - label: Mail
            name: mail
            widget: string
          - label: Text
            name: text
            widget: markdown
